name: reis
channels:
- defaults
- plotly
dependencies:
- mkl_random=1.2.2
- plotly=5.13.0
- pip=22.3.1
- openpyxl=3.0.10
- mkl_fft=1.3.1
- pandas=1.5.2

- pip:
  - git+https://github.com/isisim/pypcd.git
  - dash[diskcache]
  - dash-bootstrap-components
  - patool
  - gdown
  - tqdm
  - scikit-learn
  - -e .
